#!/bin/bash

#MOUNT REMOTE STORE
store_root="/media/ostore"
key=`mount | grep $store_root`
if [ "r$key" == "r" ]; then
    echo "Mount remote store"
    mount $store_root
else
    echo "Is not mount remote store"
fi

#CONFIG ARCHIVER APPS 
ENV_APP=/usr/bin/python
SCRIPT_APP=/opt/tools/backup/archver.py
BACKUP_DIRS="/home/dds/ /etc/nginx/"
ARHC_NAME="dds"
DST_DIR="$store_root/DDBackup/dd_dds"
if [ ! -d "$DST_DIR" ]; then
  mkdir -p $DST_DIR
fi
#Create archive
$ENV_APP $SCRIPT_APP "$BACKUP_DIRS" $DST_DIR $ARHC_NAME

# Unmount remote dir
umount $store_root
